// Layer 1: Metadata signal detection
// Supports both YouTube's legacy videoRenderer and new lockupViewModel formats.

// ---------------------------------------------------------------------------
// Signal dictionaries
// ---------------------------------------------------------------------------

const AI_HASHTAGS = new Set([
  "#aigenerated", "#aiart", "#aivideo", "#aianimation", "#aifilm",
  "#aimusic", "#generativeai", "#aiartwork", "#aiartist",
  "#midjourney", "#stablediffusion", "#dalle", "#dalle3", "#sora",
  "#runwayml", "#runwaygen", "#pikaart", "#pikalabs", "#udiomusic",
  "#sunoai", "#aivoice", "#aicovers", "#texttoimage", "#texttovideo",
  "#imagineai", "#leonardoai", "#adobefirefly", "#heygen", "#synthesia",
]);

const AI_TOOLS = [
  "midjourney", "stable diffusion", "dall-e", "dall·e", "openai sora",
  "runway ml", "runwayml", "runway gen", "pika labs", "pikalabs",
  "udio", "suno", "elevenlabs", "eleven labs", "heygen", "synthesia",
  "d-id", "kling ai", "luma dream machine", "leonardo ai",
  "adobe firefly", "invideo ai", "pictory", "fliki", "steve ai",
  "kaiber", "genmo", "haiper", "minimax video", "vidu",
];

const AI_PHRASES = [
  "ai generated", "ai-generated", "made with ai", "created with ai",
  "ai created", "ai made", "generated by ai", "ai artwork", "ai video",
  "artificially generated", "generative ai", "gen ai",
  "text to video", "text-to-video", "text to image", "text-to-image",
  "this video was made using ai", "100% ai", "fully ai",
  "ai voiceover", "ai narration", "ai voice", "voiced by ai",
  "ai music", "ai animation", "ai film", "ai movie",
  "neural network generated", "diffusion model",
];

// "AI [verb]s ..." pattern — AI as the performing subject in the title.
// Lower weight because it has more false positives than explicit phrases.
const AI_SUBJECT_VERBS = /\bai\s+(interview|narrate|voice|sing|play|recreate|generate|create|draw|paint|write|read|explain|answer|tell|show|make|build|design|predict|respond|react|cover|perform|act|speak|host|present|review|summarize|analyz|translat|imagin|resurrect|reviv|bring)s?\b/i;

const WEIGHTS = {
  youtubeDisclosure: 0.95,
  aiHashtag:         0.80,
  aiTool:            0.75,
  aiPhrase:          0.70,
  aiSubjectVerb:     0.50, // "AI interviews...", "AI narrates...", etc.
  channelName:       0.35,
};

// ---------------------------------------------------------------------------
// Page bridge — reads window.ytInitialData from the MAIN world
// ---------------------------------------------------------------------------

let _bridgeInjected = false;

function ensureBridgeInjected() {
  if (_bridgeInjected) return Promise.resolve();
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = chrome.runtime.getURL("page-bridge.js");
    script.onload  = () => { script.remove(); resolve(); };
    script.onerror = () => { script.remove(); resolve(); };
    document.documentElement.appendChild(script);
    _bridgeInjected = true;
  });
}

function requestYtInitialData() {
  return new Promise((resolve) => {
    const handler = (event) => {
      if (event.source !== window) return;
      if (event.data?.type !== "AICD_YT_DATA_RESPONSE") return;
      window.removeEventListener("message", handler);
      resolve(event.data.payload ?? null);
    };
    window.addEventListener("message", handler);
    window.postMessage({ type: "AICD_REQUEST_YT_DATA" }, "*");
    setTimeout(() => { window.removeEventListener("message", handler); resolve(null); }, 3000);
  });
}

// ---------------------------------------------------------------------------
// Meta cache
// ---------------------------------------------------------------------------

let _metaCache = null;
let _pageChannelId = null; // channel page fallback — all cards share one channel

function invalidateMetaCache() {
  _metaCache = null;
  _pageChannelId = null;
  _bridgeInjected = false;
}

async function initLayer1() {
  _metaCache = new Map();
  await ensureBridgeInjected();

  // Index initial page data
  const data = await requestYtInitialData();
  if (data) {
    walkForVideos(data, _metaCache);
    // Channel pages: extract page-level channelId from the header so cards
    // that omit per-card channel info can still get a channelId.
    if (!_pageChannelId) _pageChannelId = extractPageChannelId(data);
  }

  // Index continuation data as the user scrolls or navigates
  window.addEventListener("message", (event) => {
    if (event.source !== window) return;
    if (event.data?.type !== "AICD_YT_CONTINUATION") return;
    if (!_metaCache) return;
    walkForVideos(event.data.payload, _metaCache);
  });

}

// ---------------------------------------------------------------------------
// Walker — handles both lockupViewModel (2024+) and legacy videoRenderer
// ---------------------------------------------------------------------------

function walkForVideos(root, map) {
  const stack = [root];
  while (stack.length) {
    const node = stack.pop();
    if (!node || typeof node !== "object") continue;

    if (Array.isArray(node)) {
      for (const item of node) stack.push(item);
      continue;
    }

    // ── New format: lockupViewModel ──────────────────────────────────────
    if (node.contentType === "LOCKUP_CONTENT_TYPE_VIDEO" && node.contentId) {
      const meta = buildLockupMeta(node);
      if (meta.title) map.set(node.contentId, meta);
    }

    // ── Legacy format: videoRenderer ────────────────────────────────────
    if (typeof node.videoId === "string" && node.title) {
      map.set(node.videoId, buildMeta(node));
    }

    for (const val of Object.values(node)) {
      if (val && typeof val === "object") stack.push(val);
    }
  }
}

// ---------------------------------------------------------------------------
// Metadata extractors
// ---------------------------------------------------------------------------

/** lockupViewModel (YouTube 2024+) */
function buildLockupMeta(renderer) {
  const lmvm  = renderer.metadata?.lockupMetadataViewModel;
  const title = lmvm?.title?.content ?? "";

  // Channel name + channelId live in the first non-empty metadataRow part.
  const rows = lmvm?.metadata?.contentMetadataViewModel?.metadataRows ?? [];
  let channel = "";
  let channelId = "";
  outer: for (const row of rows) {
    for (const part of (row.metadataParts ?? [])) {
      const text = part?.text?.content ?? part?.text?.simpleText ?? "";
      if (text) {
        channel = text;
        // Try to find the browseId in commandRuns
        const runs = part?.text?.commandRuns ?? [];
        for (const run of runs) {
          const id = run?.onTap?.innertubeCommand?.browseEndpoint?.browseId;
          if (id) { channelId = id; break; }
        }
        break outer;
      }
    }
  }

  return { title, description: "", channel, channelId, badges: [], tags: [] };
}

/** Legacy videoRenderer and gridVideoRenderer */
function buildMeta(renderer) {
  // gridVideoRenderer (channel pages) uses shortBylineText instead of ownerText
  const channelId =
    renderer.ownerText?.runs?.[0]?.navigationEndpoint?.browseEndpoint?.browseId ??
    renderer.longBylineText?.runs?.[0]?.navigationEndpoint?.browseEndpoint?.browseId ??
    renderer.shortBylineText?.runs?.[0]?.navigationEndpoint?.browseEndpoint?.browseId ??
    "";
  const channel =
    extractText(renderer.ownerText ?? renderer.longBylineText ?? renderer.shortBylineText) ?? "";
  return {
    title:       extractText(renderer.title)           ?? "",
    description: extractText(renderer.descriptionSnippet) ?? "",
    channel,
    channelId,
    badges:      extractBadgeLabels(renderer),
    tags:        Array.isArray(renderer.tags) ? renderer.tags : [],
  };
}

/**
 * Extract the page-level channelId from ytInitialData.
 * Only populated on channel pages (/@handle/videos, /channel/UCxxx/...).
 */
function extractPageChannelId(data) {
  // Older YouTube: header.c4TabbedHeaderRenderer.channelId
  const fromHeader = data?.header?.c4TabbedHeaderRenderer?.channelId;
  if (fromHeader) return fromHeader;
  // Most YouTube versions: metadata.channelMetadataRenderer.externalId (reliable)
  const fromMeta = data?.metadata?.channelMetadataRenderer?.externalId;
  if (fromMeta) return fromMeta;
  // URL fallback for /channel/UCxxx paths
  const m = window.location.pathname.match(/^\/channel\/(UC[\w-]+)/);
  return m?.[1] ?? null;
}

function extractText(obj) {
  if (!obj) return "";
  if (typeof obj === "string")    return obj;
  if (obj.content)                return obj.content;   // lockupViewModel style
  if (obj.simpleText)             return obj.simpleText;
  if (Array.isArray(obj.runs))    return obj.runs.map((r) => r.text ?? "").join("");
  return "";
}

function extractBadgeLabels(renderer) {
  return [renderer.badges, renderer.ownerBadges]
    .filter(Boolean).flat()
    .map((b) => b?.metadataBadgeRenderer?.label ?? b?.metadataBadgeRenderer?.tooltip ?? "")
    .filter(Boolean)
    .map((s) => s.toLowerCase());
}

// ---------------------------------------------------------------------------
// Shadow DOM helpers
// ---------------------------------------------------------------------------

function shadowQuery(root, selector) {
  if (!root) return null;
  const hit = root.querySelector?.(selector);
  if (hit) return hit;
  for (const el of root.querySelectorAll?.("*") ?? []) {
    if (el.shadowRoot) {
      const result = shadowQuery(el.shadowRoot, selector);
      if (result) return result;
    }
  }
  return null;
}

function getVideoId(cardEl) {
  const link =
    shadowQuery(cardEl, "a#thumbnail") ??
    shadowQuery(cardEl, "a[href*='/watch']") ??
    shadowQuery(cardEl, "a[href*='/shorts/']");
  if (!link?.href) return null;
  try {
    const url = new URL(link.href);
    const v = url.searchParams.get("v");
    if (v) return v;
    // Shorts: /shorts/VIDEO_ID
    const m = url.pathname.match(/^\/shorts\/([\w-]+)/);
    return m?.[1] ?? null;
  } catch { return null; }
}

function getCardTitle(cardEl) {
  // #video-title works for legacy videoRenderer cards
  const legacyTitle =
    shadowQuery(cardEl, "#video-title")?.textContent?.trim() ??
    shadowQuery(cardEl, "yt-formatted-string#video-title")?.textContent?.trim();
  if (legacyTitle) return legacyTitle;

  // For lockupViewModel cards, the thumbnail <a> has aria-label = video title
  const thumbLabel = shadowQuery(cardEl, "a#thumbnail")?.getAttribute("aria-label");
  if (thumbLabel) return thumbLabel;

  return "";
}

function getChannelId(cardEl) {
  const videoId = getVideoId(cardEl);
  if (videoId) {
    const cached = _metaCache?.get(videoId);
    if (cached?.channelId) return cached.channelId;
  }
  // DOM fallback: find a /channel/UC... link inside the card.
  const link =
    shadowQuery(cardEl, "a.yt-simple-endpoint[href*='/channel/']") ??
    shadowQuery(cardEl, "#channel-name a") ??
    shadowQuery(cardEl, "yt-formatted-string.ytd-channel-name a");
  if (link?.href) {
    const m = link.href.match(/\/channel\/(UC[\w-]+)/);
    if (m) return m[1];
  }
  // Page-level fallback: on a channel's /videos page all cards share one channel.
  return _pageChannelId ?? "";
}

function getChannelName(cardEl) {
  const videoId = getVideoId(cardEl);
  if (videoId) {
    const cached = _metaCache?.get(videoId);
    if (cached?.channel) return cached.channel;
  }
  return shadowQuery(cardEl, "#channel-name")?.textContent?.trim() ?? "";
}

// ---------------------------------------------------------------------------
// Signal checks
// ---------------------------------------------------------------------------

function hasYoutubeDisclosure(meta) {
  return meta.badges.some(
    (b) => b.includes("ai") || b.includes("altered") || b.includes("synthetic")
  );
}

function hasAiHashtag(text) {
  return [...text.matchAll(/#\w+/g)]
    .map((m) => m[0].toLowerCase())
    .some((tag) => AI_HASHTAGS.has(tag));
}

function hasAiTool(text) {
  return AI_TOOLS.some((tool) => text.includes(tool));
}

function hasAiPhrase(text) {
  return AI_PHRASES.some((phrase) => text.includes(phrase));
}

function hasAiSubjectVerb(title) {
  return AI_SUBJECT_VERBS.test(title);
}

function hasAiChannelName(name) {
  return /\bai\b|a\.i\.|artificial intelligence|generated|syntheti/.test(name);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

function analyzeLayer1(cardEl) {
  const cache = _metaCache ?? new Map();
  const videoId = getVideoId(cardEl);

  const meta = (videoId && cache.get(videoId)) ?? {
    title:       getCardTitle(cardEl),
    description: "",
    channel:     "",
    badges:      [],
    tags:        [],
  };

  const combined = [meta.title, meta.description, ...meta.tags]
    .join(" ").toLowerCase();

  let score = 0;
  const triggered = [];

  if (hasYoutubeDisclosure(meta))      { score += WEIGHTS.youtubeDisclosure; triggered.push("disclosure"); }
  if (hasAiHashtag(combined))          { score += WEIGHTS.aiHashtag;         triggered.push("hashtag"); }
  if (hasAiTool(combined))             { score += WEIGHTS.aiTool;            triggered.push("tool"); }
  if (hasAiPhrase(combined))           { score += WEIGHTS.aiPhrase;          triggered.push("phrase"); }
  if (hasAiSubjectVerb(meta.title))    { score += WEIGHTS.aiSubjectVerb;     triggered.push("ai-subject-verb"); }
  if (hasAiChannelName(meta.channel))  { score += WEIGHTS.channelName;       triggered.push("channel"); }

  score = Math.min(score, 1.0);

  return score;
}
