// Layer 1: Metadata signal detection
// Supports both YouTube's legacy videoRenderer and new lockupViewModel formats.

// ---------------------------------------------------------------------------
// Signal dictionaries
// ---------------------------------------------------------------------------

const AI_HASHTAGS = new Set([
  "#aigenerated", "#aiart", "#aivideo", "#aianimation", "#aifilm",
  "#aimusic", "#generativeai", "#aiartwork", "#aiartist",
  "#midjourney", "#stablediffusion", "#dalle", "#dalle3", "#sora",
  "#runwayml", "#runwaygen", "#pikaart", "#pikalabs", "#udiomusic",
  "#sunoai", "#aivoice", "#aicovers", "#texttoimage", "#texttovideo",
  "#imagineai", "#leonardoai", "#adobefirefly", "#heygen", "#synthesia",
]);

const AI_TOOLS = [
  "midjourney", "stable diffusion", "dall-e", "dall·e", "openai sora",
  "runway ml", "runwayml", "runway gen", "pika labs", "pikalabs",
  "udio", "suno", "elevenlabs", "eleven labs", "heygen", "synthesia",
  "d-id", "kling ai", "luma dream machine", "leonardo ai",
  "adobe firefly", "invideo ai", "pictory", "fliki", "steve ai",
  "kaiber", "genmo", "haiper", "minimax video", "vidu",
];

const AI_PHRASES = [
  "ai generated", "ai-generated", "made with ai", "created with ai",
  "ai created", "ai made", "generated by ai", "ai artwork", "ai video",
  "artificially generated", "generative ai", "gen ai",
  "text to video", "text-to-video", "text to image", "text-to-image",
  "this video was made using ai", "100% ai", "fully ai",
  "ai voiceover", "ai narration", "ai voice", "voiced by ai",
  "ai music", "ai animation", "ai film", "ai movie",
  "neural network generated", "diffusion model",
];

// "AI [verb]s ..." pattern — AI as the performing subject in the title.
// Lower weight because it has more false positives than explicit phrases.
const AI_SUBJECT_VERBS = /\bai\s+(interview|narrate|voice|sing|play|recreate|generate|create|draw|paint|write|read|explain|answer|tell|show|make|build|design|predict|respond|react|cover|perform|act|speak|host|present|review|summarize|analyz|translat|imagin|resurrect|reviv|bring)s?\b/i;

const WEIGHTS = {
  youtubeDisclosure: 0.95,
  aiHashtag:         0.80,
  aiTool:            0.75,
  aiPhrase:          0.70,
  aiSubjectVerb:     0.50, // "AI interviews...", "AI narrates...", etc.
  channelName:       0.35,
};

// ---------------------------------------------------------------------------
// Page bridge — reads window.ytInitialData from the MAIN world
// ---------------------------------------------------------------------------

let _bridgeInjected = false;

function ensureBridgeInjected() {
  if (_bridgeInjected) return Promise.resolve();
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = chrome.runtime.getURL("page-bridge.js");
    script.onload  = () => { script.remove(); resolve(); };
    script.onerror = () => { script.remove(); resolve(); };
    document.documentElement.appendChild(script);
    _bridgeInjected = true;
  });
}

function requestYtInitialData() {
  return new Promise((resolve) => {
    const handler = (event) => {
      if (event.source !== window) return;
      if (event.data?.type !== "AICD_YT_DATA_RESPONSE") return;
      window.removeEventListener("message", handler);
      resolve(event.data.payload ?? null);
    };
    window.addEventListener("message", handler);
    window.postMessage({ type: "AICD_REQUEST_YT_DATA" }, "*");
    setTimeout(() => { window.removeEventListener("message", handler); resolve(null); }, 3000);
  });
}

// ---------------------------------------------------------------------------
// Meta cache
// ---------------------------------------------------------------------------

let _metaCache = null;

function invalidateMetaCache() {
  _metaCache = null;
  _bridgeInjected = false;
}

async function initLayer1() {
  _metaCache = new Map();
  await ensureBridgeInjected();

  // Index initial page data
  const data = await requestYtInitialData();
  if (data) walkForVideos(data, _metaCache);

  // Index continuation data as the user scrolls or navigates
  window.addEventListener("message", (event) => {
    if (event.source !== window) return;
    if (event.data?.type !== "AICD_YT_CONTINUATION") return;
    if (!_metaCache) return;
    const before = _metaCache.size;
    walkForVideos(event.data.payload, _metaCache);
    }
  });

}

// ---------------------------------------------------------------------------
// Walker — handles both lockupViewModel (2024+) and legacy videoRenderer
// ---------------------------------------------------------------------------

function walkForVideos(root, map) {
  const stack = [root];
  while (stack.length) {
    const node = stack.pop();
    if (!node || typeof node !== "object") continue;

    if (Array.isArray(node)) {
      for (const item of node) stack.push(item);
      continue;
    }

    // ── New format: lockupViewModel ──────────────────────────────────────
    if (node.contentType === "LOCKUP_CONTENT_TYPE_VIDEO" && node.contentId) {
      const meta = buildLockupMeta(node);
      if (meta.title) map.set(node.contentId, meta);
    }

    // ── Legacy format: videoRenderer ────────────────────────────────────
    if (typeof node.videoId === "string" && node.title) {
      map.set(node.videoId, buildMeta(node));
    }

    for (const val of Object.values(node)) {
      if (val && typeof val === "object") stack.push(val);
    }
  }
}

// ---------------------------------------------------------------------------
// Metadata extractors
// ---------------------------------------------------------------------------

/** lockupViewModel (YouTube 2024+) */
function buildLockupMeta(renderer) {
  const lmvm  = renderer.metadata?.lockupMetadataViewModel;
  const title = lmvm?.title?.content ?? "";

  // Channel name lives in the first non-empty metadataRow part
  const rows = lmvm?.metadata?.contentMetadataViewModel?.metadataRows ?? [];
  let channel = "";
  outer: for (const row of rows) {
    for (const part of (row.metadataParts ?? [])) {
      const text = part?.text?.content ?? part?.text?.simpleText ?? "";
      if (text) { channel = text; break outer; }
    }
  }

  return { title, description: "", channel, badges: [], tags: [] };
}

/** Legacy videoRenderer */
function buildMeta(renderer) {
  return {
    title:       extractText(renderer.title)                                ?? "",
    description: extractText(renderer.descriptionSnippet)                   ?? "",
    channel:     extractText(renderer.ownerText ?? renderer.longBylineText) ?? "",
    badges:      extractBadgeLabels(renderer),
    tags:        Array.isArray(renderer.tags) ? renderer.tags : [],
  };
}

function extractText(obj) {
  if (!obj) return "";
  if (typeof obj === "string")    return obj;
  if (obj.content)                return obj.content;   // lockupViewModel style
  if (obj.simpleText)             return obj.simpleText;
  if (Array.isArray(obj.runs))    return obj.runs.map((r) => r.text ?? "").join("");
  return "";
}

function extractBadgeLabels(renderer) {
  return [renderer.badges, renderer.ownerBadges]
    .filter(Boolean).flat()
    .map((b) => b?.metadataBadgeRenderer?.label ?? b?.metadataBadgeRenderer?.tooltip ?? "")
    .filter(Boolean)
    .map((s) => s.toLowerCase());
}

// ---------------------------------------------------------------------------
// Shadow DOM helpers
// ---------------------------------------------------------------------------

function shadowQuery(root, selector) {
  if (!root) return null;
  const hit = root.querySelector?.(selector);
  if (hit) return hit;
  for (const el of root.querySelectorAll?.("*") ?? []) {
    if (el.shadowRoot) {
      const result = shadowQuery(el.shadowRoot, selector);
      if (result) return result;
    }
  }
  return null;
}

function getVideoId(cardEl) {
  const link =
    shadowQuery(cardEl, "a#thumbnail") ??
    shadowQuery(cardEl, "a[href*='/watch']");
  if (!link?.href) return null;
  try { return new URL(link.href).searchParams.get("v") ?? null; }
  catch { return null; }
}

function getCardTitle(cardEl) {
  // #video-title works for legacy videoRenderer cards
  const legacyTitle =
    shadowQuery(cardEl, "#video-title")?.textContent?.trim() ??
    shadowQuery(cardEl, "yt-formatted-string#video-title")?.textContent?.trim();
  if (legacyTitle) return legacyTitle;

  // For lockupViewModel cards, the thumbnail <a> has aria-label = video title
  const thumbLabel = shadowQuery(cardEl, "a#thumbnail")?.getAttribute("aria-label");
  if (thumbLabel) return thumbLabel;

  return "";
}

// ---------------------------------------------------------------------------
// Signal checks
// ---------------------------------------------------------------------------

function hasYoutubeDisclosure(meta) {
  return meta.badges.some(
    (b) => b.includes("ai") || b.includes("altered") || b.includes("synthetic")
  );
}

function hasAiHashtag(text) {
  return [...text.matchAll(/#\w+/g)]
    .map((m) => m[0].toLowerCase())
    .some((tag) => AI_HASHTAGS.has(tag));
}

function hasAiTool(text) {
  return AI_TOOLS.some((tool) => text.includes(tool));
}

function hasAiPhrase(text) {
  return AI_PHRASES.some((phrase) => text.includes(phrase));
}

function hasAiSubjectVerb(title) {
  return AI_SUBJECT_VERBS.test(title);
}

function hasAiChannelName(name) {
  return /\bai\b|a\.i\.|artificial intelligence|generated|syntheti/.test(name);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

function analyzeLayer1(cardEl) {
  const cache = _metaCache ?? new Map();
  const videoId = getVideoId(cardEl);

  const meta = (videoId && cache.get(videoId)) ?? {
    title:       getCardTitle(cardEl),
    description: "",
    channel:     "",
    badges:      [],
    tags:        [],
  };

  const combined = [meta.title, meta.description, ...meta.tags]
    .join(" ").toLowerCase();

  let score = 0;
  const triggered = [];

  if (hasYoutubeDisclosure(meta))      { score += WEIGHTS.youtubeDisclosure; triggered.push("disclosure"); }
  if (hasAiHashtag(combined))          { score += WEIGHTS.aiHashtag;         triggered.push("hashtag"); }
  if (hasAiTool(combined))             { score += WEIGHTS.aiTool;            triggered.push("tool"); }
  if (hasAiPhrase(combined))           { score += WEIGHTS.aiPhrase;          triggered.push("phrase"); }
  if (hasAiSubjectVerb(meta.title))    { score += WEIGHTS.aiSubjectVerb;     triggered.push("ai-subject-verb"); }
  if (hasAiChannelName(meta.channel))  { score += WEIGHTS.channelName;       triggered.push("channel"); }

  score = Math.min(score, 1.0);

  return score;
}
